//
//  FTNotebookEventTracker.swift
//  Noteshelf3
//
//  Created by Sameer Hussain on 02/02/24.
//  Copyright © 2024 Fluid Touch Pte Ltd. All rights reserved.
//

import Foundation

class FTNotebookEventTracker {
    static let toolbar_back_tap = "toolbar_back_tap"
    static let toolbar_undo_tap = "toolbar_undo_tap"
    static let toolbar_redo_tap = "toolbar_redo_tap"
    static let toolbar_focusmode_toggle = "toolbar_focusmode_toggle"
    static let focusmode_gesture_toggle = "focusmode_gesture_toggle"
    static let toolbar_addmenu_tap = "toolbar_addmenu_tap"
    static let toolbar_more_tap = "toolbar_more_tap"
    static let toolbar_right_arrow_tap = "toolbar_right_arrow_tap"
    static let toolbar_left_arrow_tap = "toolbar_left_arrow_tap"
    static let toolbar_tools_swipe = "toolbar_tools_swipe"
    static let nbk_more_share_tap = "nbk_more_share_tap"
    static let nbk_more_share_currentpage_tap = "nbk_more_share_currentpage_tap"
    static let nbk_more_share_allpages_tap = "nbk_more_share_allpages_tap"
    static let nbk_more_share_selectpages_tap = "nbk_more_share_selectpages_tap"
    static let nbk_more_present_tap = "nbk_more_present_tap"
    static let nbk_more_gotopage_tap = "nbk_more_gotopage_tap"
    static let nbk_more_zoombox_tap = "nbk_more_zoombox_tap"
    static let nbk_more_rotatepage_tap = "nbk_more_rotatepage_tap"
    static let nbk_more_rotate_clockwise_tap = "nbk_more_rotate_clockwise_tap"
    static let nbk_more_rotate_180_tap = "nbk_more_rotate_180_tap"
    static let nbk_more_rotate_anticlockwise_tap = "nbk_more_rotate_anticlockwise_tap"
    static let nbk_more_changetemplate_tap = "nbk_more_changetemplate_tap"
    static let nbk_more_saveastemplate_tap = "nbk_more_saveastemplate_tap"
    static let nbk_more_getinfo_tap = "nbk_more_getinfo_tap"
    static let nbk_more_getinfo_title_tap = "nbk_more_getinfo_title_tap"
    static let nbk_more_getinfo_gotopage_tap = "nbk_more_getinfo_gotopage_tap"
    static let nbk_more_gestures_tap = "nbk_more_gestures_tap"
    static let nbk_more_help_tap = "nbk_more_help_tap"
    static let nbk_more_moresettings_tap = "nbk_more_moresettings_tap"
    static let nbk_moresettings_password_tap = "nbk_moresettings_password_tap"
    static let nbk_moresettings_addtisiri_tap = "nbk_moresettings_addtisiri_tap"
    static let nbk_moresettings_synctoevernote_tap = "nbk_moresettings_synctoevernote_tap"
    static let nbk_moresettings_scrolling_tap = "nbk_moresettings_scrolling_tap"
    static let nbk_moresettings_hideappUI_toggle = "nbk_moresettings_hideappUI_toggle"
    static let nbk_moresettings_hyperlinks_toggle = "nbk_moresettings_hyperlinks_toggle"
    static let nbk_moresettings_autolock_toggle = "nbk_moresettings_autolock_toggle"
    static let nbk_moresettings_stylus_tap = "nbk_moresettings_stylus_tap"
    static let applepencil_useapplepencil_toggle = "applepencil_useapplepencil_toggle"
    static let applepencil_pressuresensitivity_toggle = "applepencil_pressuresensitivity_toggle"
    static let applepencil_doubletapaction_tap = "applepencil_doubletapaction_tap"
    static let applepencil_doubletapaction_selected = "applepencil_doubletapaction_selected"
    static let nbk_addmenu_segment_tap = "nbk_addmenu_segment_tap"
    static let nbk_addpage_newpage_tap = "nbk_addpage_newpage_tap"
    static let nbk_addpage_choosetemplate_tap = "nbk_addpage_choosetemplate_tap"
    static let nbk_addpage_pagefromphoto_tap = "nbk_addpage_pagefromphoto_tap"
    static let nbk_addpage_scan_tap = "nbk_addpage_scan_tap"
    static let nbk_addpage_pagefromcamera_tap = "nbk_addpage_pagefromcamera_tap"
    static let nbk_addpage_importdocument_tap = "nbk_addpage_importdocument_tap"
    static let nbk_addpage_pastefromclipboard_tap = "nbk_addpage_pastefromclipboard_tap"
    static let nbk_addmenu_photo_tap = "nbk_addmenu_photo_tap"
    static let nbk_addmenu_camera_tap = "nbk_addmenu_camera_tap"
    static let nbk_addmenu_recordaudio_tap = "nbk_addmenu_recordaudio_tap"
    static let nbk_addmenu_emojis_tap = "nbk_addmenu_emojis_tap"
    static let nbk_addmenu_stickers_tap = "nbk_addmenu_stickers_tap"
    static let nbk_addmenu_savedclips_tap = "nbk_addmenu_savedclips_tap"
    static let nbk_addmenu_importmedia_tap = "nbk_addmenu_importmedia_tap"
    static let nbk_addmenu_applewatch_tap = "nbk_addmenu_applewatch_tap"
    static let nbk_addmenu_webclip_tap = "nbk_addmenu_webclip_tap"
    static let nbk_addmenu_unsplash_tap = "nbk_addmenu_unsplash_tap"
    static let nbk_addmenu_pixabay_tap = "nbk_addmenu_pixabay_tap"
    static let nbk_addmenu_emojis_emoji_tap = "nbk_addmenu_emojis_emoji_tap"
    static let nbk_addmenu_emojis_search_tap = "nbk_addmenu_emojis_search_tap"
    static let nbk_addmenu_emojis_category_tap = "nbk_addmenu_emojis_category_tap"
    static let nbk_addmenu_stickers_category_tap = "nbk_addmenu_stickers_category_tap"
    static let nbk_addmenu_stickers_subcategory_tap = "nbk_addmenu_stickers_subcategory_tap"
    static let nbk_addmenu_stickers_sticker_tap = "nbk_addmenu_stickers_sticker_tap"
    static let nbk_addmenu_unsplash_image_tap = "nbk_addmenu_unsplash_image_tap"
    static let nbk_addmenu_pixabay_imag_tap = "nbk_addmenu_pixabay_imag_tap"
    static let share_selectpages_page_select = "share_selectpages_page_select"
    static let share_selectpages_page_unselect = "share_selectpages_page_unselect"
    static let share_selectpages_selectall_tap = "share_selectpages_selectall_tap"
    static let share_selectpages_selectnone_tap = "share_selectpages_selectnone_tap"
    static let share_selectpages_done_tap = "share_selectpages_done_tap"
    static let share_selectpages_share_tap = "share_selectpages_share_tap"
    static let share_format_tap = "share_format_tap"
    static let share_savetocamera_tap = "share_savetocamera_tap"
    static let share_options_tap = "share_options_tap"
    static let share_options_pagetemplate_toggle = "share_options_pagetemplate_toggle"
    static let share_options_titleandpageno_toggle = "share_options_titleandpageno_toggle"
    static let share_share_tap = "share_share_tap"
    static let share_cancel_tap = "share_cancel_tap"
    static let nbk_swipetoaddpage = "nbk_swipetoaddpage"
    static let nbk_swipe_newpage_tap = "nbk_swipe_newpage_tap"
    static let nbk_swipe_choosetemplate_tap = "nbk_swipe_choosetemplate_tap"
    static let nbk_swipe_importdocument_tap = "nbk_swipe_importdocument_tap"
    static let nbk_swipe_more_tap = "nbk_swipe_more_tap"


    static func trackNotebookEvent(with value: String, params: [String: Any]? = nil) {
        track(value, params: params,screenName: FTScreenNames.notebook)
    }
}
