//
//  FTDefaults.h
//  Noteshelf
//
//  Created by Developer on 11/10/13.
//
//

#ifndef Noteshelf_FTDefaults_h
#define Noteshelf_FTDefaults_h

#define WRITING_STYLE_SELECTED      @"WRITING_STYLE_SELECTED" //
#define EVERNOTE_PUBLISH_PURCHASED  @"EVERNOTE_PUBLISH_PURCHASED"
#define EVERNOTE_PUBLISH_ON_WIFI_ONLY @"EVERNOTE_PUBLISH_ON_WIFI_ONLY" //
#define EVERNOTE_ALWAYS_PUBLISH_NEW_BOOKS @"EVERNOTE_ALWAYS_PUBLISH_NEW_BOOKS" //
#define EVERNOTE_EXPORT_AS_SINGLE_NOTE @"EVERNOTE_EXPORT_AS_SINGLE_NOTE" //

#define EVERNOTE_PUBLISH_ERROR @"EVERNOTE_PUBLISH_ERROR"
#define EVERNOTE_LAST_PUBLISH_TIME @"EVERNOTE_LAST_PUBLISH_TIME"
#define EN_PUBLISH_ERR_SHOW_SUPPORT @"EN_PUBLISH_ERR_SHOW_SUPPORT"
#define EN_LOGGED_USERNAME @"EN_LOGGED_USERNAME"
#define EN_USEDSPACE @"EN_USEDSPACE"
#define EN_USEDSPACEPERCENT @"EN_USEDSPACEPERCENT"

#define BACKUP_ERROR @"LAST_BACK_UP_ERROR"

#define PENCIL_EVER_CONNECTED @"PENCIL_EVER_CONNECTED"

#endif
