# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

#default_platform(:ios)

platform :ios do
    desc "Push a new beta build to TestFlight"
    lane :beta do

        app_identifier = "com.fluidtouch.noteshelf3-beta"

        reset_git_repo(force: true, disregard_gitignore: false)
        ensure_git_branch(branch: 'develop')
        git_pull
        
        build_number = latest_testflight_build_number(app_identifier: app_identifier) + 1
        releaseNotes = changelog_from_git_commits(pretty: "- %s", date_format: "short")
        increment_build_number({ build_number: build_number })

        
        build_app(workspace: "Noteshelf.xcworkspace",
                  scheme: "Noteshelf3",
                  configuration: "Beta",
                  export_options: "beta_export_options.plist",
                  silent: true)
                  
                  notification(subtitle: "🛠️ Finished Building", message: "Ready to upload...")

                  upload_to_testflight(skip_waiting_for_build_processing: true,
                                       app_platform:"ios",
                                       ipa: "build/NS3 Beta.ipa",
				       archivePath: "build/Noteshelf3.xcarchive",
                                       app_identifier: app_identifier,
                                       changelog: releaseNotes)

                  notification(subtitle: "✅ Finished Uploading", message: "Uploaded successfully")
                  slack(message: "✅ iOS app Finished Uploading",
                        default_payloads: [:git_branch, :git_author],
                        payload: {
                        "Build Number" => build_number,
                        "Release Notes" => releaseNotes
                        })
    end

    desc "Push a new beta build to AppStore"
    lane :release do
        app_identifier = "com.fluidtouch.noteshelf3"

       reset_git_repo(force: true, disregard_gitignore: false)
       ensure_git_branch(branch: 'develop')
       git_pull

        build_number = latest_testflight_build_number(app_identifier: app_identifier) + 1
        releaseNotes = changelog_from_git_commits(pretty: "- %s", date_format: "short")
        increment_build_number({ build_number: build_number })


        build_app(workspace: "Noteshelf.xcworkspace",
                  scheme: "Noteshelf3",
                  configuration: "Release",
                  export_options: "beta_export_options.plist",
                  silent: true)

                  notification(subtitle: "🛠️ Finished Building", message: "Ready to upload...")

                  upload_to_testflight(skip_waiting_for_build_processing: true,
                                       app_platform:"ios",
                                       ipa: "build/Noteshelf 3.ipa",
				       archivePath: "build/Noteshelf3.xcarchive",
                                       app_identifier: app_identifier,
                                       changelog: releaseNotes)

                  notification(subtitle: "✅ Finished Uploading", message: "Uploaded successfully")
                  slack(message: "✅ iOS app Finished Uploading",
                        default_payloads: [:git_branch, :git_author],
                        payload: {
                        "Build Number" => build_number,
                        "Release Notes" => releaseNotes
                        })
    end
    
    error do |lane, exception|
        notification(subtitle: "⛔️ Error", message: exception.to_s)
    end
end

platform :mac do
    lane :beta do

        app_identifier = "com.fluidtouch.noteshelf3-beta"

        reset_git_repo(force: true, disregard_gitignore: false)
       ensure_git_branch(branch: 'develop')
        git_pull


        build_number = latest_testflight_build_number(app_identifier: app_identifier,
                                                      platform: "osx") + 1
        releaseNotes = changelog_from_git_commits(pretty: "- %s", date_format: "short")
        increment_build_number({ build_number: build_number })
        
        build_mac_app(workspace: "Noteshelf.xcworkspace",
                      scheme: "Noteshelf3",
                      destination: 'platform=macOS,arch=x86_64,variant=Mac Catalyst',
                      installer_cert_name: '3rd Party Mac Developer Installer: Fluid Touch Pte. Ltd. (CNTLGGQX2J)',
                      configuration: "Beta",
                      export_options: "beta_export_options_mac.plist",
                      silent: true)
                      
                      notification(subtitle: "🛠️ Catalyst Finished Building",
                                   message: "Catalyst Ready to upload...")

                      upload_to_testflight(skip_waiting_for_build_processing: true,
                                           app_identifier: app_identifier,
                                           app_platform:"osx",
        				   ipa: "build/NS3 Beta.ipa",
					   archivePath: "build/Noteshelf3.xcarchive",
                                           changelog: releaseNotes)

                      notification(subtitle: "✅ Catalyst Finished Uploading",
                                   message: "Catalyst Uploaded successfully")

                      slack(message: "✅ Mac app Finished Uploading",
                            default_payloads: [:git_branch, :git_author],
                            payload: {
                            "Build Number" => build_number,
                            "Release Notes" => releaseNotes
                            })

    end

    lane :release do

        reset_git_repo(force: true, disregard_gitignore: false)
       	ensure_git_branch(branch: 'develop')
        git_pull
        app_identifier = "com.fluidtouch.noteshelf3"

        build_number = latest_testflight_build_number(app_identifier: app_identifier,
                                                      platform: "osx") + 1
        releaseNotes = "Release Notes from Fastlane"
        increment_build_number({ build_number: build_number })

        build_mac_app(workspace: "Noteshelf.xcworkspace",
                      scheme: "Noteshelf3",
                      destination: 'platform=macOS,arch=x86_64,variant=Mac Catalyst',
                      installer_cert_name: '3rd Party Mac Developer Installer: Fluid Touch Pte. Ltd. (CNTLGGQX2J)',
                      configuration: "Release",
                      export_options: "beta_export_options_mac.plist",
                      silent: true)

                      notification(subtitle: "🛠️ Catalyst Finished Building",
                                   message: "Catalyst Ready to upload...")

                      upload_to_testflight(skip_waiting_for_build_processing: true,
                                           app_platform:"osx",
        				   ipa: "build/Noteshelf 3.ipa",
					   archivePath: "build/Noteshelf3.xcarchive",
                                           app_identifier: app_identifier,
                                           changelog: releaseNotes)

                      notification(subtitle: "✅ Mac Finished Uploading", message: "Catalyst Uploaded successfully")
                      slack(message: "✅ Mac app Finished Uploading",
                            default_payloads: [:git_branch, :git_author],
                            payload: {
                            "Build Number" => build_number,
                            "Release Notes" => releaseNotes
                            })

    end

    error do |lane, exception|
        notification(subtitle: "⛔️ Error", message: exception.to_s)
        slack(message: exception.to_s)
    end
end
